- hosts: webservers
  vars:
    nginx_port: 3200
    root_dir: /usr/share/nginx/html
    server_name: "This is server {{ansible_facts['nodename']}}!"
    date: "{{ '%d-%B-%Y' }}"  
  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
      become: yes

    - name: copy html from template
      ansible.builtin.template:
        src: templates/index.html.j2
        dest: "{{root_dir}}/index.html"
      become: yes


    - name: copy nginx.conf from template
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx
      become: yes

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes
